services:
  api:
    image: fastapi-jwt-auth-image
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
